In [3]:
import sys
sys.path.append("../../py_interface/")
from mstat import indexes

*** using base directory: /home/brt/code/matching_statistics/indexed_ms/fast_ms/bin ***

In [4]:

def get_s(fname):
    with open(fname) as fd:
        return fd.read().strip()

s = get_s('m.s')
t = get_s('m.t')
print(s)
print(t)
idx = (indexes.MatchingStatistics.ms_table(t, s).assign(psum = lambda x: x.MS.cumsum() - 1))
idx

bebbeabcaecdbddddaccdeacdebeeeaedbebdacecbdceaebbbbabcbacebabecdcebbaabdddaebbedbaccbdbadcaccdcdbeadabcbebddcdacdbeedcabbdcacdae
abbabaaabbaa

    t_i  MS  nzeros    ms  runs  psum
i
-1        1       0          -1     0
 0    a   3       3  0001     0     3
 1    b   4       2   001     0     7
 2    b   3       0     1     1    10
 3    a   2       0     1     1    12
 4    b   3       2   001     0    15
 5    a   2       0     1     1    17
 6    a   3       2   001     0    20
 7    a   3       1    01     0    23
 8    b   4       2   001     0    27
 9    b   3       0     1     1    30
 10   a   2       0     1     1    32
 11   a   1       0     1     1    33

In [14]:
idx.psum.iloc[0]

1